# [[commands]]
# name = "google"
# cmd = "ping google.com"
#
# [[commands]]
# name = "duckgo"
# cmd = "ping duck.com"

[[commands]]
name = "github"
cmd = "ping github.com"

[[commands]]
name = "tw"
cmd = "tailwindcss --input ./input.css --output ./styles.css --watch"
